- sc2ts/alignments.py
- sc2ts/core.py
- sc2ts/inference.py
tsinfer is well isolated now, should be reasonably easy to start pulling things apart and also testing them
> Refactor matching code path

- sc2ts/inference.py
Remove tsinfer and Biopython based version as neither is reliable.
> Revert to scipy-based UPGMA tree

- sc2ts/utils.py
> Fix error in recombinants per day plot

- sc2ts/utils.py
Allow for GC like things in report()
> Improvements to recombinant handling

- sc2ts/nextstrain.py
So that we don't get confused. Also make a helper function for loading from a path
> Rename nextstrain JSON functions to "nextclade"

- sc2ts/nextstrain.py
No tests. Works OK for me though.
> Functions to extract the nextstrain nexus files

- notebooks/qc-template.ipynb
- sc2ts/utils.py
More information on sites and mutations.
> Site utils

- sc2ts/utils.py
> Use imputated pango if available

- sc2ts/utils.py
> Fix off by one error

- notebooks/qc-template.ipynb
- sc2ts/utils.py
Closes #108
How does this look at @szhan?
The only thing I've changed is to output "Unknown" instead of "Recombinant" for pango lineage status, which seems less confusing to me.
> Add function to systematise exporting recombinants

- sc2ts/utils.py
I think there's a bug in the current `export_recombinants` function because we report the parents and the mutations from the zeroth element of the matches metadata array, and I think this is (sometimes?) the *backwards* pass, so doesn't correspond to the tree seq.
This PR uses the term "backward" and "forward" rather than indexes, so we don't get confused.
> Change list to dict

- sc2ts/utils.py
Damn. Only just spotted this bug. Fortunately it doesn't seem to make a difference to the plots
> Correct wrong variables

- sc2ts/utils.py
Add an extra column to say if the HMM-reported breakpoint does not make it into the final ARG
> Classify non tree hmms

- sc2ts/utils.py
Allow the labels in the sample_subgraph plot to be shown or hidden
Stacked onto #135
> Sample subgraph labels and colours

- sc2ts/utils.py
To match Ana's new lineage imputation metadata keys.
Relevant to #134 as it raises an error if the metadata key isn't present.
Instead of saving both designations in the TreeInfo class, you have to pick one at the start. I thought that would reduce the amount of output from the various tabulating functions, and I think we probably want to pick just one classification or the other, not use both. But happy for this to change, obviously.
> TreeInfo can use alternative Pango classifications

- sc2ts/utils.py
As discussed by Ana. Doesn't look great at the moment with large labels, so needs some tweaking:
> Always add number of descendant samples

- sc2ts/utils.py
So that an arbitrary set of nodes can be plotted as a graph. Also provide functions to calculate the nodes to pass into plot_subgraph, and use these to replace the precious sample_subgraph function.
> Make plot_subgraph func

- sc2ts/utils.py
Also put recurrent mutations in bold
> Allow numbers of descendant samples to be shown even on nonsample nodes

- sc2ts/inference.py
> Add details about copying path and mutations to node metadata

- sc2ts/cli.py
- sc2ts/inference.py
- sc2ts/utils.py
- tests/test_inference.py
- tests/test_utils.py
> Implement HMM cost to filter samples

- sc2ts/inference.py
- tests/test_inference.py
- tests/test_utils.py
> Filter samples by HMM cost without match grouping

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_inference.py
- tests/test_utils.py
> Dump pickled objects of samples filtered by HMM cost

- setup.cfg
> Pin zarr < 2.18

- sc2ts/cli.py
- sc2ts/inference.py
> Reconsider filtered samples from the past N consecutive days

- sc2ts/inference.py
Partially address #193. The previous PR #194 addresses removing the samples outside the window for reconsideration, but not the samples added back in. This can still result in the same samples added more than once. This PR provides a temporary solution, but it need to be replaced later when the list of excluded samples is handled using a better mechanism.
> Remove samples added back after reconsidering

- sc2ts/inference.py
> Put added-back samples at the correct times

- sc2ts/utils.py
> Fix max_masked_sites_per_sample when generating TreeInfo

- pyproject.toml
- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_inference.py
- tests/test_utils.py
- tests/util.py
> Use match DB

- sc2ts/cli.py
- sc2ts/inference.py
Some minor tweaks to get running on initial tests.
The stop argument is handy to get things running initially with a high hmm cost, and then switch back to something reasonable.
> Add stop to cli

- sc2ts/core.py
Temporary update to try this out.
> Add top 15 mutation outlier sites to exclude list

- sc2ts/cli.py
- sc2ts/core.py
- sc2ts/inference.py
Makes exporting alignments easier (although it will insert the ancestral state at problematic sites)
> Improvements

- notebooks/test_ts.ipynb
> Add notebook to examine test ARG

- sc2ts/utils.py
Sorry - I am the "from sklearn import tree" criminal! I don't remember doing this.
> Fixing sklearn import

- sc2ts/inference.py
- sc2ts/info.py
> Initial clade info + group retrospectives by location

- sc2ts/info.py
> Add info for several major VoCs

- sc2ts/cli.py
- sc2ts/info.py
- tests/test_info.py
> Add tally_lineages tool

- pyproject.toml
- sc2ts/inference.py
- tests/test_tree_hueristics.py
For testing. I think this works, but I'm getting test suite errors elsewhere, so can't be certain. Can you try it @jeromekelleher . You'll need to `pip install biotite`.
> Switch in biotite NJ algorithm for local tree building

- run.sh
> Fix skip date in run script

- sc2ts/alignments.py
- tests/test_inference.py
> Disregard excluded sites when computing base composition

- sc2ts/info.py
- tests/test_info.py
> Count mutations above all nodes

- sc2ts/info.py
> Add LineageDetail for Beta and Gamma

- sc2ts/cli.py
- tests/test_cli.py
Here's the proposal for adding resource usage to provenance @benjeffery. I think this could be copied back to tsinfer and would work fine there too.
I'll try it out with sc2ts here and see how well it works.
> Add resources used to provenance

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_cli.py
Will be a faff to update test cases, so keeping things as they are for now until we review the effect.
> Temporarily disable ucsc problematic sites

- sc2ts/inference.py
Metadata for trees inferred since parallel preprocessing was introduced should be regarded as suspect
> Fix bug shuffling metadata

- sc2ts/info.py
- tests/test_info.py
> Plot RE nodes as open circles

- sc2ts/inference.py
- sc2ts/metadata.py
- tests/test_inference.py
> Add a progress bar for sample DB prep

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_inference.py
> Use low-level tsinfer components directly

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_cli.py
- tests/test_inference.py
> Implement run_hmm API endpoint

- .github/workflows/ci.yml
- sc2ts/cli.py
- sc2ts/dataset.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_dataset.py
Also remove reorder-dataset CLI
> Remove requirement for date_field

- sc2ts/info.py
> Fix bug in computing immediate reversions

- sc2ts/cli.py
- sc2ts/inference.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_inference.py
The metadata trimming stuff is a bit annoying, as we're using a bunch of different words for the same thing and ideally we should standardise on the same terminology as VCF Zarr and Viridian. I don't know if I have the stomach for more metadata complexity, right now, though.
> Postprocess

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_cli.py
- tests/test_inference.py
Missing some important provenance and tracking information from postprocess
> Add postprocess provenance

- sc2ts/info.py
And expose `ti.copying_pattern()` so we can use it independently.
Default view is now like this:
> Change the copying pattern table to the new style

- sc2ts/dataset.py
- tests/test_dataset.py
This adds a function ``Dataset.write_fasta(file, list_of_sample_ids)``
> Adds write_fasta method to Dataset

- sc2ts/cli.py
- sc2ts/inference.py
- tests/test_cli.py
- tests/test_inference.py
Also renames map_deletions to map_parsimony
> Insert missing sites

- sc2ts/dataset.py
- tests/test_dataset.py
Smooths out and improves performance
> Readahead for variants()

- sc2ts/inference.py
- tests/test_inference.py
Somewhat inelegant, but this is now working and correctly rewiring the BA.2 recombinant
> Add ability to create a TS with an intermediate node

- sc2ts/info.py
Will help when making illustrative figures
> Minor improvements to layout for copying patterns

- sc2ts/info.py
A minro change to allow more informative output (e.g. put pango labels for parents)
> Allow class / labels to be set in copying pattern table
