jeromekelleher/sc2ts

sc2ts/nextstrain.py
As the nextstrain JSON doesn't have any sites, so the intersection with that tree results in no sites at all
=> Ability not to filter out sites on intersection

sc2ts/utils.py
Replaces #116, as discussed. Returns one row for each breakpoint. We can easily subset down to rows with only a single breakpoint (i.e. 2 parents) by
```python
df.drop_duplicates('node', keep=False)
```
or average the metrics across all the breakpoints in a node by
```python
df.groupby('node').mean()
```
So I think this is a nice and flexible output.
=> add export_recombination_node_breakpoints

sc2ts/utils.py
I've added some code to systematically get all the recombinants from the ARG and the information about MRCAs for each partial edge. It's in the function get_recombinant_mrca_table (takes < 1 second to run on long ARG).
I've used this function to add some more filters on the ``export_recombinants`` function (renamed to export_one_break_recombinants). The point of this consistency filtering is to try and whittle down to things that are fairly consistent among the different runs of the HMM. The reasoning is that if we get radically different things from the three different runs in terms of the parents, then that probably isn't something worth reporting in a publication.
=> Get breakpoint MRCAs systematically and update single-break recombinant export

notebooks/lineage-graphs.ipynb, notebooks/lineage-imputation.ipynb, sc2ts/utils.py
Was missing out some lineages because (for example) EPI_ISL_000000.1 in the ts metadata appears only as EPI_ISL_000000 in the GISAID metadata file.  Still a hundred missing or so, but for some other reasons.
=> Fixing missing GISAID lineages

sc2ts/utils.py
We need to be able to turn off `plt.show()` when scriptifying this plot to create figures for publication (rather than outputting to a notebook). The easiest is not to call `show()` when a plot axis has already been specified, which is what we do when creating pdfs for publication.
=> Only plot if no axis defined

sc2ts/utils.py
This places edge labels containing mutations at the bottom of the edge, and changes the format for recombination positions to put the numbers on 2 lines, with "≥" and "<" in front of the numbers to distinguish from mutations.
=> Rework sample_subgraph plot, particularly labels

sc2ts/utils.py, tests/test_inference.py, tests/test_utils.py, tests/util.py
Allows us to create a ts for plotting that doesn't have singleton recombinants and their associated recombination nodes.
=> Add `dereference_singleton_recombinants`

sc2ts/utils.py
Are we OK to set the index on the dataframe returned by `treeinfo.summary()`? That makes it easier to do e.g.
```python
ts.summary().loc["latest_sample"]
```
=> Minor util improvements

sc2ts/alignments.py
Sample sequences may be come in lowercase, for example, in the latest batch of sequences kindly prepared by Martin Hunt from the Iqbal group. Here is a simple tweak to convert lowercased sequences into uppercased sequences, which can be mapped to the uppercase nucleotide characters in `core.ALLELES`. Note that a sequence is stored as a Numpy array (dtype="<U1"), and the entire array is uppercased.
=> Uppercase input sequences

sc2ts/inference.py
This fixes a logical bug, which led to the list of reconsidered samples being extended only if it is not empty. This means none of the excluded samples are reconsidered if we do not provide a base ts when running `daily-extend`.
=> Fix adding excluded samples to an empty list of reconsidered samples

sc2ts/utils.py
Note this probably isn't correct in general, but at least lets things run. We need improved metadata here on recombinants (see #233)
=> Fix overly strict causal sample date

sc2ts/cli.py, sc2ts/inference.py
Some useful updates here that make matching substantially faster.
Previous experiments that I did showed that we get exactly the same results for any precision>=12, so I left it at that value and moved on. I tried varying the precision values here and noticed some odd properties, and then realised that the precision value is bound up with the magnitude of the input rho and mu parameters, and if these are too small, then we will necessarily have to have a high precision in order to work with them. So, I rescaled the (arbitrarily chosen) mu value so that our parameters are as large as possible (ish). This then lets us use a more useful range of precision values.
Under this new LS parameter rescaling, we get identical results to the old runs with a precision of 6. Having higher precision …
=> Rescale ls params and adaptive precision

sc2ts/core.py, sc2ts/inference.py, tests/test_inference.py, tests/test_utils.py
Makes exporting alignments easier (although it will insert the ancestral state at problematic sites)
=> Add reference as sample, and include reference sequence in ts

pyproject.toml, sc2ts/inference.py, tests/test_inference.py
Requires https://github.com/tskit-dev/tsinfer/pull/959
Haven't tried this out at scale yet, but setting a threshold of mu**k to detect sequences with k mismatches seems much more intuitive to me than all the other fiddling around we had to do.
=> Experiment with alternative HMM implementation

sc2ts/inference.py, sc2ts/metadata.py, tests/test_inference.py
Trying out running in three passes with a likelihood threshold of 0, mu, and rho^2  * mu^5 (which is about 1e-10, and around the same as 10 mutations). I've arbitrarily chosen this as the most unlikely thing we'd want to characterise exactly.
Just seeing if this gives us the same results as the previous pass with completely unlimited precision and improves run-time.
=> Tweak dynamic parameters

sc2ts/inference.py, tests/test_inference.py
Because it slows down inference a lot. We have only a few recombinants, so we don't effectively parallelise, and we do it three times. Also, we're doing some expensive matching on things which will mostly not get into the final ARG.
So, additional HMM runs is something we do as a postprocess step.
=> Move recombinant processing offline

get_lineage_data.sh, sc2ts/core.py, sc2ts/data/lineages.json, sc2ts/info.py
cc @szhan @hyanwong  - this adds the basic Pango lineage data from cov-lineages, cut down to the minimal useful fields. There's function to get it (``get_cov_lineages_data``)
It's not perfect, but it's a reasonable thing to compare to in terms of understanding how we're doing with backward and forward time travellers (which are also a thing, btw)
=> Pango lineage data

pyproject.toml, sc2ts/info.py
No tests: is there a test ARG we can call a function like this on?
Use like e.g.
```python
pango = "B.1.1.7"
ti.plot_pango_lineage_subtree(pango, collapse_tracked=0.99365, node_labels={}, time_scale="time")
```
Currently waiting on https://github.com/tskit-dev/tskit/pull/3015 to be merged before this actually works.
=> Show trees of Pango lineages

sc2ts/info.py
This helps when dissecting a Pango lineage
=> Allow tracked nodes to be specified by strain / nodeID too

sc2ts/info.py, sc2ts/utils.py
And fix a bug whereby bespoke labels led to an error
=> Make mutation labelling more flexible

sc2ts/info.py
But also allow calendar date, if required.
This makes it much easier to compare plots from ARGs with different endpoints. We need to make sure that we run dating with e.g. `constr_iterations = 500` for the dates to be sensible, though.
=> Default subplots to time difference from first sample

sc2ts/core.py, sc2ts/inference.py, sc2ts/info.py, tests/conftest.py, tests/test_inference.py, tests/test_info.py
=> Updates for sample group infrastructure

sc2ts/dataset.py, sc2ts/inference.py, tests/test_dataset.py, tests/test_inference.py
=> Make date_field parametrisable

sc2ts/dataset.py
This seemed like the neatest API for mapping deletions, as we require a Dataset object, and can add methods to it easily enough, i.e.
```python
ds = sc2ts.Dataset("../data/viridian_2024-04-29.alpha1.zarr.zip")
ts = tszip.load("../data/find_problematic_v2-2023-01-01.ts.tsz")
start = 11284
end = 11302
del_ts = ds.map_deletions_to_ts(ts, start, end)
```
I have coded it so that the first sample could be Wuhan, or not. I have also put a stub for a test in, but I'm not sure how to actually test it, as I don't know if we have a test tree sequence equivalent of fx_dataset with the same named samples.
=> Add map_deletions_to_ts as Dataset method

sc2ts/info.py
I think it's worth merging this tiny fix, so that notebooks continue to work even if #480 has not been merged
=> Get TreeInfo working even if sc2ts metadata missing

sc2ts/info.py
Colours near-adjacent sites in orange, and properly aligns them. Also halves the size of the saved files (good for large notebooks), but does use a stylesheet.
The resulting images like like this:
Compared to previously:
=> Better display of adjacent runs

pyproject.toml, sc2ts/cli.py, sc2ts/inference.py, tests/test_cli.py, tests/test_inference.py
To get the metadata out in pandas form of a set of trees returned by this, you can do
```python
data = tsp.nodes_metadata
cols = {k: data[k].astype(str) for k in data.dtype.names}
df = pd.DataFrame(cols)
```
I'll follow up with a public function that does this and computes a bunch of other fast-stuff about nodes for a sc2ts ARG.
=> Add minimise metadata to generate the analysis version

sc2ts/cli.py, tests/test_cli.py
Otherwise we can't date the trees
=> Move the zero edge dropping to minimise metadata
